#!/bin/sh

# change directory to script's directory
cd -P -- "$(dirname -- "$0")"

# get one line from list_todo.txt
# no file locking, sorry
read line < list_todo.txt

if [ "z$DEBUG" = "z1" ]; then echo "line = $line"; fi

# remove first line in list_todo.txt
tail -n +2 list_todo.txt > list_tmp
chmod --reference=list_todo.txt list_tmp
mv list_tmp list_todo.txt

if [ ! -z "$line" ]
then
  ARG="-q --no-playlist"
  if [ "z$DEBUG" = "z1" ]; then ARG="--no-playlist"; fi

  # call dockerized youtube-dl
  docker run -it --rm \
      -v $(pwd)/downloads:/downloads \
      kastaneda/ytdlui youtube-dl $ARG "$line"

  # minimalistic error logging
  if [ $? -eq 0 ]
  then
    echo "$line" >> list_done.txt
  else
    echo "$line" >> list_errors.txt
  fi
fi
