#!/bin/sh
cd -P -- "$(dirname -- "$0")"

# no file locking, sorry
read line < list_todo.txt

tail -n +2 list_todo.txt > list_tmp
chmod --reference=list_todo.txt list_tmp
mv list_tmp list_todo.txt

if [ ! -z "$line" ]
then
  docker run -it --rm \
      -v $(pwd)/downloads:/media \
      -e LC_ALL=en_US.UTF-8 \
      ytdl youtube-dl -q "$line"

  if [ $? -eq 0 ]
  then
    echo "$line" >> list_done.txt
  else
    echo "$line" >> list_errors.txt
  fi
fi
